services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    volumes:
      - ../:/var/www/html/sys-recolection:delegated
    expose:
      - 9000
    depends_on:
      - db
    networks:
      - laravel
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ../:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - laravel
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    networks:
      - laravel
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306

  adminer:
    image: adminer
    restart: always
    container_name: db_adminer
    ports:
      - 8081:8080
    networks:
      - laravel

volumes:
  db_data:


networks:
  laravel:
    driver: bridge
